Разметка главной страницы
htmlacademy-htmlcss/235311-nerds-30 pull request #2
Opened 2021-01-30 17:19 UTC by Alexander-Dronov

Разметка главной страницы

2021-01-30 18:46 UTC, YaroslavWD requested changes

2021-01-30 18:46 UTC, YaroslavWD commented on index.html
> +      <li><a href="#">Магазин</a></li>
Здесь нужна ссылка на внутреннюю страницу

2021-01-30 18:46 UTC, YaroslavWD commented on index.html
> +<header>
`<head>` и `<body>` должны лежать на одном уровне вложенности, лишние отступы. 
`<header>` вложен в `<body>`

2021-01-30 18:46 UTC, YaroslavWD commented on index.html
> +  <main>
`<main>` на одном уровне с `<header>`

2021-01-30 18:46 UTC, YaroslavWD commented on index.html
> +        <ul>
лишний отступ у `<ul>`

2021-01-30 18:46 UTC, YaroslavWD commented on index.html
> +          <button type="button">Узнать больше</button>
Здесь нужна  ссылка

2021-01-30 18:46 UTC, YaroslavWD commented on index.html
> +          <button type="button">Заказать</button>
Здесь нужна ссылка и в аналогичных блоках

2021-01-30 18:46 UTC, YaroslavWD commented on index.html
> +      <h2>Мы-маленькая, но годрдая<br>
`<br>` здесь не нужен

2021-01-30 18:46 UTC, YaroslavWD commented on index.html
> +      <p>Исповедуем принципы минимализма и частоты. Ставим математический расчет<br>
Здесь <br> тоже не нужен

2021-01-30 19:39 UTC, Alexander-Dronov commented
Исправил вложенность, добавил ссылки на внутренние страницы, добавил ссылки на кнопки, убрал лишние переносы.

2021-02-01 06:27 UTC, YaroslavWD requested changes

2021-02-01 06:27 UTC, YaroslavWD commented on index.html
> +      <li><a href="index.html">Контакты</a></li>
Здесь должны быть заглушки,` #!`  страница сама на себя не должна ссылаться

2021-02-01 06:27 UTC, YaroslavWD commented on index.html
> +            <img src="https://via.placeholder.com/199x68" alt="Логотип HTML Academy"></a>
Забыл тег `<a>` на новую строку

2021-02-01 06:27 UTC, YaroslavWD commented on index.html
> +          <img src="https://via.placeholder.com/81x81" alt="VK"></a>
отступ и перенос ссылки

2021-02-01 06:27 UTC, YaroslavWD commented on index.html
> +            <img src="https://via.placeholder.com/81x81" alt="FaceBook"></a>
перенос ссылки

2021-02-01 06:27 UTC, YaroslavWD commented on index.html
> +            <img src="https://via.placeholder.com/81x81" alt="Instagram"></a>
перенос ссылки

2021-02-01 12:17 UTC, Alexander-Dronov commented
перенос ссылки и заглушки

2021-02-02 06:52 UTC, YaroslavWD approved these changes

2021-02-02 06:52 UTC, merged