Create catalog.html
htmlacademy-htmlcss/235311-nerds-30 pull request #3
Opened 2021-02-02 11:18 UTC by Alexander-Dronov

Разметка каталога

2021-02-02 16:36 UTC, YaroslavWD requested changes

2021-02-02 16:36 UTC, YaroslavWD commented on catalog.html
> +    <a>
Это внутренняя страница, здесь нужен путь на главную

2021-02-02 16:36 UTC, YaroslavWD commented on catalog.html
> +      <li><a href="index.html">Контакты</a></li>
Здесь нужны везде заглушки, тут страницы сами на себя ссылаются.

2021-02-02 16:36 UTC, YaroslavWD commented on catalog.html
> +            <p>от 0 до 15000</p>
это два поля ввода

2021-02-02 16:36 UTC, YaroslavWD commented on catalog.html
> +                    <input type="radio" name="net" value="adapted" id="adapted-net" checked>
лишние отступы

2021-02-02 16:36 UTC, YaroslavWD commented on catalog.html
> +                    <input type="checkbox" name="features" id="slider" checked>
атрибут name у чекбоксов должен быть разный

2021-02-02 16:36 UTC, YaroslavWD commented on catalog.html
> +        <ul>
лишние отступы

2021-02-02 16:36 UTC, YaroslavWD commented on catalog.html
> +            <img src="https://via.placeholder.com/11x10" alt="Стрелка вверх">
лишние отступы

2021-02-02 16:36 UTC, YaroslavWD commented on catalog.html
> +        </a>
Здесь у тебя должна быть обертка, пусть с изображением + всплывающий блок по наведению. Этот блок не будет изображением, там текст + кнопка(ссылка)

2021-02-02 16:36 UTC, YaroslavWD commented on catalog.html
> +                <a href="#">1</a>
у текущей страницы не нужен атрибут

2021-02-03 05:13 UTC, Alexander-Dronov commented
Исправления в разметке каталога

2021-02-04 06:01 UTC, YaroslavWD requested changes

2021-02-04 06:01 UTC, YaroslavWD commented on catalog.html
> +            </div>
Отступы, и аналогичная разметка должна быть у всех остальных блоков. Они абсолютно такие же

2021-02-04 06:01 UTC, YaroslavWD commented on catalog.html
> +                <lable for="rubber-net">Резиновая</lable>
Отступы у label и input

2021-02-06 14:19 UTC, Alexander-Dronov commented
Исправил разметку товара на список, разметил для каждого товара дополнительный блок, поправил вложенность в разметка

2021-02-07 08:47 UTC, YaroslavWD requested changes

2021-02-07 08:47 UTC, YaroslavWD commented on catalog.html
> +  <a href="#">Корзина</a>
отступ

2021-02-07 08:47 UTC, YaroslavWD commented on catalog.html
> + <section>
Отступы

2021-02-07 08:47 UTC, YaroslavWD commented on catalog.html
> +   <li>По цене</li>
Ссылки

2021-02-07 18:54 UTC, Alexander-Dronov commented
исправлены отступы, добавлены ссылки

2021-02-08 18:27 UTC, YaroslavWD approved these changes

2021-02-08 18:27 UTC, YaroslavWD commented on catalog.html
> +                <label fore="advantages">Блок преимуществ</label>
Лишняя буква forE

2021-02-08 18:27 UTC, YaroslavWD commented on catalog.html
> +                <label fore="news">Новости</label>
Лишняя буква forE

2021-02-08 18:27 UTC, YaroslavWD commented on catalog.html
> +              <liclass="block-item">
Пропустил пробел

2021-02-08 18:27 UTC, YaroslavWD commented on catalog.html
> +          <li class="sort-item">По цене</li>
Так и не добавил ссылки

2021-02-08 18:27 UTC, YaroslavWD commented on catalog.html
> +              <img src="img/img-pink 1.png" width="359" height="578" alt="Пинк">
Пробел в пути

2021-02-08 18:27 UTC, YaroslavWD commented on catalog.html
> +              <img src="img/img-barbershop 1.png" width="359" height="578" alt="Бородинский">
Пробел в пути

2021-02-08 18:27 UTC, YaroslavWD commented on catalog.html
> +              <img src="img/img-mishka 1.png" width="359" height="578" alt="Мишка">
Пробел в пути

2021-02-08 18:27 UTC, merged